#!/bin/bash

pushd $(dirname $0) >/dev/null 2>&1
here=$(pwd)
popd >/dev/null 2>&1

srcdir="$ECSRCDIR"
if [ -z "$srcdir" ]; then
  # See if we're in a source directory already.
  searchdir=$(pwd)
  while [ "$searchdir" != "/" ]; do
    if [ -x "$searchdir/modules/scriptlets/exe/eclua" ]; then
      srcdir="$searchdir"
      break
    fi
    searchdir=$(dirname $searchdir)
  done
fi

if [ -z "$srcdir" ]; then
  /opt/msys/ecelerity/bin/eclua \
    $here/lualint $*
else
  # Run against development branch.
  LD_LIBRARY_PATH=$srcdir $srcdir/modules/scriptlets/exe/eclua \
    -E $srcdir/modules:$srcdir/modules/cloud \
    $here/lualint $*
fi
