#!/bin/bash

pushd $(dirname $0) >/dev/null 2>&1
here=$(pwd)
popd >/dev/null 2>&1

# Turn on relaxed mode by default.
if [ -z "$ECSRCDIR" ]; then
  /opt/msys/ecelerity/bin/eclua \
    $here/lualint $*
else
  # Run against development branch.
  LD_LIBRARY_PATH=$ECSRCDIR $ECSRCDIR/modules/scriptlets/exe/eclua \
    -E $ECSRCDIR/modules \
    $here/lualint $*
fi
